### PR TITLE
Jest tests

### PR DESCRIPTION
**Pull request by BarryThePenguin**
This is quite large, so I've tried to break each commit into a logical step.

[travis](https://travis-ci.org/BarryThePenguin/typography.js/builds/167995393) and [codecov](https://codecov.io/gh/BarryThePenguin/typography.js/tree/8bf4415a74074f5b70720fa9f8d0f2dd55dde6f4)

## added and updated dependancies

here I'm adding and updating the dependancies needed to run tests using Jest. I added react as a dev dependancies as it's needed for some of the tests. Also added some scripts and config for Jest needed in other commits

## added flow types

this commit can be removed, but it helped me a lot while writing the tests. From what I read, adding flow types to git is helpful as it ensures all developers receive a consistent set of types and any changes to types go through the regular code review process

## add tests

I tried my best to add tests that made sense of the api. Flow does a good job of ensuring the structure of things are correct, but the structure tests should give an idea when api's change.

## add snapshots

the great thing about Jest is snapshot testing. This works great for what typography.js is doing. This allows relatively small tests to pick up any change to how typography internals work. This also means changes to the output can be reviewed in pull requests 🎉 

## add ci steps

this uses travis.ci and codecov, but can be changed up for any alternatives

## editorconfig

I find an editorconfig to be very helpful 🍤 

## etc...

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey! This looks super awesome! Sorry for the slow feedback — in middle of Gatsby R&D sprint. Will give this a thorough review soon!

**Comment by KyleAMathews** [comment]
This is a really excellent PR 💯 thanks!

**Comment by BarryThePenguin** [comment]
Woo! 🎉

**Comment by KyleAMathews** [comment]
Going to work on #92 and then make a new release!

**Pull request merged**
