### PR TITLE
Don't wrap "serif" or "sans-serif" in quotes

### PR DESCRIPTION
**Pull request by TrevorBurnham**
Fix for #122.

I made this change without running the project locally, so please check that this actually works before merging. 😅

### CODE REVIEW

**Comment by TrevorBurnham** [comment]
Sure thing: 86f7e75

I tried doing `npm test` locally, but it failed due to linter errors… 545 of them! 👾👾👾

**Comment by KyleAMathews** [comment]
Yeah we don't pay too much attention to the lint results, probably should remove them. Prettier does most of what I want eslint to do. Perhaps use eslint trimmed down to a few useful checks.

**Comment by KyleAMathews** [comment]
Thanks for the fix! I'll put a release out shortly.

**Comment by TrevorBurnham** [comment]
Terrific!

**Pull request merged**
