### PR TITLE
Add Breakpoints support

### PR DESCRIPTION
**Pull request by TylerBarnes**
Hey Kyle! I really wanted breakpoint support so I added it. 
Afterwards I realized I forgot to disable prettier so it added a lot of small changes to the formatting of your code which I'll fix first if you're interested in merging this. 
The purpose of this pull request is to see if you're good with the way I've implemented breakpoints. If you have any feedback I can modify the code however you'd like. I think the code could be made a little more DRY and overrides could be turned into a function so it can be called inside breakpoints as well instead of at the end. I also added breakpoint support in the spot where you indicated it should be.

I wrapped the code that generates styles inside a function and then immediately called that and passed in the vertical rythm. I then also called that function for each breakpoint with a new vertical rythm for each breakpoint. New typography objects are being created for each breakpoint. Wherever the breakpoint isn't overriding the original object it will inherit from the original typography object. Afterwards the object is compared to the original object and only new declarations which aren't in the original object are being passed through. Finally the breakpoint objects are added onto the end of the original typography object in order. It works with toJSON and toString.

Let me know what you think! Hopefully this is in the direction of how you were going to implement it.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey! This does look good. Hopefully I'm going to have some significant time to return to this project in the next month or two so can work on getting this in and some other improvements.

BTW, have you seen this technique? Might be fun to automatically add "fluid typography" support for smoothly transitioning between breakpoints https://css-tricks.com/snippets/css/fluid-typography/

**Comment by chocobuckle** [comment]
@TylerBarnes Could you possibly give some examples of how to use breakpoints with your fork please? Thanks for your work! :)

**Comment by TylerBarnes** [comment]
@chocobuckle Make sure you switch to the breakpoints branch first and import the typographyjs index file. 
I can't remember right now but you may need to yarn/npm install and run a build command to generate the index file.

```javascript
{
  bodyFontFamily: ["HalisGr", "helvetica"],
  headerFontFamily: ["HalisGr", "helvetica"],
  bodyWeight: 100,
  headerWeight: 400,
  baseFontSize: "15px",
  baseLineHeight: 1.6,
  scaleRatio: 2,
  blockMarginBottom: 0,
  includeNormalize: false,
  breakpoints: {
    "@media screen and (min-width:800px)": {
      // any valid media query.
      scaleRatio: 2.5 // Override the default scale
    },
    "@media screen and (min-width:1200px)": {
      // any valid media query.
      scaleRatio: 3 // Override the default scale
    },
    "@media screen and (min-width:1500px) and (max-height: 900px)": {
      // any valid media query.
      baseFontSize: "17px",
      scaleRatio: 4 // Override the default scale
    },
    "@media screen and (min-width:1500px) and (min-height: 900px), screen and (min-width: 1900px)": {
      // any valid media query.
      scaleRatio: 4.5 // Override the default scale
    }
  }
};
```
You can use any valid typographyjs setting within a breakpoint since each breakpoint returns a new instance of typographyjs before each instance gets merged together at the end.

**Comment by snrbrnjna** [comment]
what's going on with this? @KyleAMathews

**Comment by TylerBarnes** [comment]
@snrbrnjna haven't heard about this in a while but in the mean time I put out a forked package on npm with this functionality. `npm i tyjs` 
https://www.npmjs.com/package/tyjs

I've used this on a number of production sites and it's worked well for our team.

**Comment by snrbrnjna** [comment]
@TylerBarnes thanks, i'll give it a try. At the moment i override the styles globally outside the typography.js config. but it's ugly. 

would love ❤️to have this feature merged.

**Comment by Blackglade** [comment]
any updates on this?

**Comment by loganwishartcraig** [comment]
+1 on requesting this feature 😄

**Pull request closed without merging**
