### PR TITLE
add React.Component instead of React.creatClass in packages/react-typography/src/GoogleFont.js and TypographyStyle.js

### PR DESCRIPTION
**Pull request by guoliim**
add React.Component instead of React.creatClass in packages/react-typography/src/GoogleFont.js and TypographyStyle.js, if you think it's unnecessary，ignore them.

### CODE REVIEW

**Comment by guoliim** [comment]
maybe it's better to republish on npm if you accept the pr.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Released 0.15.10

**Comment by guoliim** [comment]
nice

**Pull request merged**
