### PR TITLE
chore (deps): support react ^18 as peerDependency in react-typography

### PR DESCRIPTION
**Pull request by vinniegarcia**

### CODE REVIEW

**Comment by creatorrr** [comment]
Unable to use library with react 18.x without this patch. @KyleAMathews any particular reason for not merging this?

**Comment by KyleAMathews** [comment]
Published

**Comment by idmadj** [comment]
@KyleAMathews 
The publication seems to have failed. Latest on npm still has:
```
"peerDependencies": {
  "react": "^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0"
},
```
Probably just needs a version bump.

**Comment by KyleAMathews** [comment]
hmm not sure why it didn't publish last time. Out now https://www.npmjs.com/package/react-typography

**Pull request merged**
